/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
ExporterVersion: 2.2.0
*/

import { useGLTF } from '@react-three/drei';
import { forwardRef } from 'react';

useGLTF.preload('copernicus.glb');

const Model = forwardRef((props, ref) => {
  const { scene } = useGLTF('copernicus.glb');

  scene.traverse((child) => {
    if (child.isMesh) {
      child.castShadow = true;
      child.receiveShadow = true;
      child.material.metalness = 0.7;
      child.material.roughness = 0.5;
      child.material.envMapIntensity = 1;
    }
  });

  // Rotate model to face the camera
  scene.rotation.y = Math.PI;
  return (
    <group ref={ref} position={[-1, -4, -3]} scale={3.2}>
      <primitive object={scene} {...props} />
    </group>
  );
});
Model.displayName = 'Model';

export default Model;
