/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
ExporterVersion: 2.2.0
*/

import { useAnimations, useGLTF, useScroll } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';
import { useEffect, useRef } from 'react';

useGLTF.preload('IonDrive.glb');

const Model = (props) => {
  const ref = useRef();
  const { scene, animations } = useGLTF('IonDrive.glb');
  const { actions } = useAnimations(animations, scene);

  useEffect(() => {
    actions['Main'].play();
  }, [actions]);

  // changing color of the model and adding glow effect
  scene.traverse((child) => {
    if (child.isMesh) {
      child.material.emissive.set('#8F00FF');
      child.material.emissiveIntensity = 0.2;
    }
  });
  return (
    <group ref={ref} position={[3, 0.5, -2]} scale={0.5}>
      <primitive object={scene} {...props} />
    </group>
  );
};

export default Model;
