/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
ExporterVersion: 2.2.0
*/

import { useGLTF } from '@react-three/drei';
import { forwardRef } from 'react';

useGLTF.preload('lieutenantHead.glb');

const Model = forwardRef((props, ref) => {
  const { scene } = useGLTF('lieutenantHead.glb');

  scene.traverse((child) => {
    if (child.isMesh) {
      child.castShadow = true;
      child.receiveShadow = true;
      child.material.metalness = 0.9;
      child.material.roughness = 0.9;
      child.material.envMapIntensity = 1;
    }
  });
  return (
    <group ref={ref} position={[-1, -0.3, -3]} scale={1.3}>
      <primitive object={scene} {...props} />
    </group>
  );
});
Model.displayName = 'Model';

export default Model;
