export { SearchIcon } from './Search';
export { ThreeDIcon } from './3D';
export { TwoDIcon } from './2D';
export { default as ArrowIcon } from './ArrowIcon';
export { default as RobotIcon } from './Robot';
export { default as LinkedInIcon } from './LinkedInIcon';
export { default as GithubIcon } from './GithubIcon';
export { default as MediumIcon } from './MediumIcon';
export { default as InstagramIcon } from './InstagramIcon';
export { default as StarIcon } from './Star';
export { default as StarTrekIcon } from './Startrek';
export { default as Redirect } from './Redirect';
